# Generated by Django 5.0.1 on 2024-01-04 02:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tour",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="tour",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tour",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="tour",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tour",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
