# Generated by Django 5.0.1 on 2024-01-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0002_alter_tour_options_tour_created_at_tour_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="ratings_qty",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
