# Generated by Django 5.0.1 on 2024-01-04 03:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0003_alter_tour_ratings_qty"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tour",
            options={"ordering": ["id", "-created_at"]},
        ),
    ]
