# Generated by Django 5.0.1 on 2024-01-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0004_alter_tour_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("moderate", "Moderate"),
                    ("difficult", "Difficult"),
                ],
                default="moderate",
                max_length=20,
            ),
        ),
    ]
