# Generated by Django 5.0.1 on 2024-01-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("guide", "Guide"),
                    ("lead-guide", "Lead Guide"),
                ],
                default="user",
                max_length=50,
            ),
        ),
    ]
