# Generated by Django 5.0.1 on 2024-01-21 03:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="start_dates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateField(), blank=True, null=True, size=None
            ),
        ),
    ]
