# Generated by Django 5.0.1 on 2024-01-21 03:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0002_tour_start_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="start_dates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateTimeField(), blank=True, null=True, size=None
            ),
        ),
    ]
